
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include_dir_merge_list template_sensors/
utility_meter: !include utilitymeter.yaml

input_number:
# https://www.bjerke-energi.se/elnat/tariffer/normaltariff-2026/
  normaltariff:
    name: "Normaltariff"
    min: 0
    max: 100
    unit_of_measurement: kWh
    step: 0.1

# Today's current top hour, to be compared to top1-3 and possibly stored
  normaltariff_daily_max:
    name: "Normaltariff daily max (06-22)"
    min: 0
    max: 100
    step: 0.01
    unit_of_measurement: "kWh"

# 1st (of 3) top hours this month
  normaltariff_top1:
    name: "Normaltariff top 1 (daily max)"
    min: 0
    max: 100
    step: 0.01
    unit_of_measurement: "kWh"

# 2nd (of 3) top hours this month
  normaltariff_top2:
    name: "Normaltariff top 2 (daily max)"
    min: 0
    max: 100
    step: 0.01
    unit_of_measurement: "kWh"

# 3rd (of 3) top hours this month
  normaltariff_top3:
    name: "Normaltariff top 3 (daily max)"
    min: 0
    max: 100
    step: 0.01
    unit_of_measurement: "kWh"
    
  min_soc:
    name: "Min SOC (%)"
    min: 5
    max: 20
    step: 1
    unit_of_measurement: "%"
    icon: mdi:battery-alert

  max_soc:
    name: "Max SOC (%)"
    min: 70
    max: 100
    step: 1
    unit_of_measurement: "%"
    icon: mdi:battery
    

input_datetime:
# Today's current top hour, to be compared to top1-3 and possibly stored
  normaltariff_daily_max_date:
    name: "Normaltariff daily max date"
    has_date: true
    has_time: false

# Date of 1st (of 3) top hours this month
  normaltariff_top1_date:
    name: "Normaltariff top1 date"
    has_date: true
    has_time: false

# Date of 2nd (of 3) top hours this month
  normaltariff_top2_date:
    name: "Normaltariff top2 date"
    has_date: true
    has_time: false

# Date of 3rd (of 3) top hours this month
  normaltariff_top3_date:
    name: "Normaltariff top3 date"
    has_date: true
    has_time: false