
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include_dir_merge_list template_sensors/
utility_meter: !include utilitymeter.yaml


input_number:
  min_soc:
    name: "Min SOC (%)"
    min: 5
    max: 20
    step: 1
    unit_of_measurement: "%"
    icon: mdi:battery-alert

  max_soc:
    name: "Max SOC (%)"
    min: 70
    max: 100
    step: 1
    unit_of_measurement: "%"
    icon: mdi:battery
    
  petrus_battery_snapshot:
    name: "Petrus battery snapshot"
    initial: 0
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "%"

input_text:
  petrus_action_snapshot:
    name: "Petrus action snapshot"
    initial: ""
    max: 255

input_datetime:
  petrus_last_seen_snapshot:
    name: "Petrus last seen snapshot"
    has_date: true
    has_time: true



recorder:
  purge_keep_days: 5
  exclude:
    entity_globs:
      - sensor.*shadow_price
      - sensor.inverter_pv_*
      - sensor.batteries_bus_*
      - sensor.solcast_pv_forecast_power_in_*
    entities:
      - sensor.power_meter_power_factor
      - sensor.power_meter_frequency
      - sensor.battery_charge_discharge_power_with_loss
      - sensor.house_consumption_power_forecast
      - sensor.haeo_planned_charging
      - sensor.haeo_planned_discharging
      - sensor.normaltariff_max_charge_power
      - sensor.current_hour

